class Meme {
  constructor(src, name) {
    this.src = src
    this.name = name
  }
}

export default [
  new Meme('1.jpg', 'Am I a Joke To You?'),
  new Meme('2.jpg', 'Bangladeshi Cake Cutting'),
  new Meme('3.jpg', 'Left Exit 12 Off Ramp'),
  new Meme('4.jpg', 'Steven Crowder\'s "Change My Mind" Campus Sign'),
  new Meme('5.jpg', 'Confused Nick Young'),
  new Meme('6.jpg', 'Distracted Boyfriend'),
  new Meme('7.jpg', 'Drake Posting'),
  new Meme('8.jpg', 'Death Knocking on Doors'),
  new Meme('9.jpg', "Gru's Plan"),
  new Meme('10.jpg', 'Ight Imma Head Out'),
  new Meme('11.jpg', 'I Think I Forgot Something'),
  new Meme('12.jpg', 'Jim Halpert Smiling Through Blinds'),
  new Meme('13.jpg', 'Dancing Joker'),
  new Meme('14.jpg', 'Joker Gets Hit By a Car'),
  new Meme('15.jpg', 'Let Me In'),
  new Meme('16.jpg', 'Me and the Boys'),
  new Meme('17.jpg', 'Mocking SpongeBob'),
  new Meme('18.jpg', 'Awkward Look Monkey Puppet'),
  new Meme('19.jpg', 'Nileseyy Niles Disappears'),
  new Meme('20.jpg', 'What the Hell Is This'),
  new Meme('21.jpg', 'Obama Awards Obama a Medal'),
  new Meme('22.jpg', 'SpongeGar'),
  new Meme('23.jpg', 'What Did You Do To My Drink?'),
  new Meme('24.jpg', 'Rev Up Those Fryers'),
  new Meme('25.jpg', "Ol' Reliable"),
  new Meme('26.jpg', 'Surprised Pikachu'),
  new Meme('27.jpg', 'Thomas Had Never Seen Such Bullshit Before'),
  new Meme('28.jpg', 'It Was Time for Thomas to Leave'),
  new Meme('29.jpg', 'Toothless Presents Himself'),
  new Meme('30.jpg', 'Tuxedo Winnie the Pooh'),
  new Meme('31.jpg', 'Vince McMahon Reaction'),
  new Meme('32.jpg', 'Who Killed Hannibal?'),
  new Meme('33.jpg', 'Woman Yelling at a Cat'),
  new Meme('34.jpg', 'Draw 25'),
  new Meme('35.jpg', 'Confused Black Girl'),
  new Meme('36.jpg', 'Sleeping Shaq'),
  new Meme('37.jpg', "They're The Same Picture"),
  new Meme('38.jpg', 'Math Lady'),
  new Meme('39.jpg', 'Unsettled Tom'),
  new Meme('40.jpg', 'I Am Once Again Asking for Your Financial Support'),
  new Meme('41.jpg', 'Ralph In Danger'),
  new Meme('42.jpg', "Carefully He's a Hero"),
  new Meme('43.jpg', 'Flex Tape'),
  new Meme('44.jpg', 'I Can See You Bitch'),
  new Meme('45.jpg', 'The Office Standoff'),
  new Meme('46.jpg', 'Squidward Looking Out the Window'),
  new Meme('47.jpg', 'Jazz Music Stops'),
  new Meme('48.jpg', 'Outstanding Move'),
  new Meme('49.jpg', 'Trust Nobody, Not Even Yourself'),
  new Meme('50.jpg', 'I diagnose you with dead'),
  new Meme('51.jpg', ''),
  new Meme('52.jpg', ''),
  new Meme('53.jpg', ''),
  new Meme('54.jpg', ''),
  new Meme('55.jpg', ''),
  new Meme('56.jpg', ''),
  new Meme('57.jpg', ''),
  new Meme('58.jpg', ''),
  new Meme('59.jpg', ''),
  new Meme('60.jpg', ''),
  new Meme('61.jpg', ''),
  new Meme('62.jpg', ''),
  new Meme('63.jpg', ''),
  new Meme('64.jpg', ''),
  new Meme('65.jpg', ''),
  new Meme('66.jpg', ''),
  new Meme('67.jpg', ''),
  new Meme('68.jpg', ''),
  new Meme('69.jpg', ''),
  new Meme('70.jpg', ''),
  new Meme('71.jpg', ''),
  new Meme('72.jpg', ''),
  new Meme('73.jpg', ''),
  new Meme('74.jpg', ''),
  new Meme('75.jpg', ''),
  new Meme('76.jpg', ''),
  new Meme('77.jpg', ''),
  new Meme('78.jpg', ''),
  new Meme('79.jpg', ''),
  new Meme('80.jpg', ''),
  new Meme('81.jpg', ''),
  new Meme('82.jpg', ''),
  new Meme('83.jpg', ''),
  new Meme('84.jpg', ''),
  new Meme('85.jpg', ''),
  new Meme('86.jpg', ''),
  new Meme('87.jpg', ''),
  new Meme('88.jpg', ''),
  new Meme('89.jpg', ''),
  new Meme('90.jpg', ''),
  new Meme('91.jpg', ''),
  new Meme('92.jpg', ''),
  new Meme('93.jpg', ''),
  new Meme('94.jpg', ''),
  new Meme('95.jpg', ''),
  new Meme('96.jpg', ''),
  new Meme('97.jpg', ''),
  new Meme('98.jpg', ''),
  new Meme('99.jpg', ''),
  new Meme('100.jpg', ''),
  new Meme('101.jpg', ''),
  new Meme('102.jpg', ''),
  new Meme('103.jpg', ''),
  new Meme('104.jpg', ''),
  new Meme('105.jpg', ''),
  new Meme('106.jpg', ''),
  new Meme('107.jpg', ''),
  new Meme('108.jpg', ''),
  new Meme('109.jpg', ''),
  new Meme('110.jpg', ''),
  new Meme('111.jpg', ''),
  new Meme('112.jpg', ''),
  new Meme('113.jpg', ''),
  new Meme('114.jpg', ''),
  new Meme('115.jpg', ''),
  new Meme('116.jpg', ''),
  new Meme('117.jpg', ''),
  new Meme('118.jpg', ''),
  new Meme('119.jpg', ''),
  new Meme('120.jpg', ''),
  new Meme('121.jpg', ''),
  new Meme('122.jpg', ''),
  new Meme('123.jpg', ''),
  new Meme('124.jpg', ''),
  new Meme('125.jpg', ''),
  new Meme('126.jpg', ''),
  new Meme('127.jpg', ''),
]
